apitest/urls.py
from django.conf.urls import url
from django.contrib import admin
from apitest.views import apis
from apitest.views import url_man
from apitest.views import host_env
from apitest.views import start
from apitest.views import users

urlpatterns = [
    url(r'^login/$',users.login,name='login'),
    url(r'^logout/$',users.logout,name='logout'),
    url(r'^urls/list/$', url_man.urlslist,name='urllist'),
    url(r'^urls/add/$', url_man.urladd,name='urladd'),
    url(r'^urls/edit/(\d+)/$', url_man.urledit,name='urledit'),
    url(r'^urls/del/(\d+)/$', url_man.urldel,name='urldel'),
    url(r'^api/list/$', apis.apilist,name='apilist'),
    url(r'^api/add/$', apis.apiadd,name='apiadd'),
    url(r'^api/edit/(\d+)/$', apis.apiedit,name='apiedit'),
    url(r'^api/del/(\d+)/$', apis.apidel,name='apidel'),
    url(r'^env/list/$', host_env.envlist, name='envlist'),
    url(r'^env/add/$', host_env.envadd, name='envadd'),
    url(r'^env/edit/(\d+)/$', host_env.envedit, name='envedit'),
    url(r'^env/del/(\d+)/$', host_env.envdel, name='envdel'),
    url(r'^start/$', start.start_test, name='start_test'),
    url(r'^result/$', start.test_result, name='test_result'),
]

restapi/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),  #administrator: root/123qwe123
    url(r'^apitest/', include('apitest.urls')),
]

apitest/models.py
from django.db import models


# Create your models here.


class UrlManage(models.Model):
    """
    url管理
    """
    urlname = models.CharField(verbose_name='url名称',max_length=128)
    func = models.CharField(verbose_name='类别名称',max_length=32)
    def __str__(self):
        return self.urlname


class ApiManage(models.Model):
    '''
    Api管理
    '''
    apiname = models.CharField(verbose_name='接口功能',max_length=32,unique=True)
    url = models.ForeignKey(verbose_name='url地址',to=UrlManage)
    header = models.CharField(verbose_name='请求头',max_length=128)
    parmary = models.CharField(verbose_name='url参数',max_length=64,null=True,blank=True)
    body = models.CharField(verbose_name='请求body',max_length=1024,null=True,blank=True)
    methor_choices = (
        (1, 'POST'),
        (2, 'GET'),
        (3, 'PUT'),
        (4, 'DELETE'),
    )
    methor = models.IntegerField(verbose_name='请求方法',choices=methor_choices)

    def __str__(self):
        return self.apiname


class RunEnv(models.Model):
    """
    运行环境
    """
    host = models.CharField(verbose_name='主机环境',max_length=32,unique=True)
    token = models.CharField(verbose_name='管理员帐号',max_length=512)
    appkey = models.CharField(verbose_name='appkey名称',max_length=32)
    def __str__(self):
        return self.host


class Test_Result(models.Model):
    """
    测试结果
    """
    api = models.CharField(verbose_name='功能接口',max_length=32,unique=True)
    status_code = models.CharField(verbose_name='返回的状态码',max_length=16)
    test_content = models.TextField(verbose_name='测试结果')
    test_data = models.DateTimeField(verbose_name='最后执行时间',auto_now=True)


class User_manage(models.Model):
    '''
    用户管理
    '''
    username = models.CharField(verbose_name='用户名',max_length=32)
    password = models.CharField(verbose_name='密码',max_length=32)
    def __str__(self):
        return self.username

apitest/views/apis.py
from django.shortcuts import render,redirect
from apitest import models
from django.urls import reverse
from apitest.form.allform import ApiModelForm


def apilist(request):
    api_queryset = models.ApiManage.objects.all()
    return render(request,'apilist.html',{'api_queryset':api_queryset})


def apiadd(request):
    '''
    添加接口
    :param request:
    :return:
    '''
    if request.method == 'GET':
        form = ApiModelForm()
        return render(request,'change.html',{'form':form})
    form = ApiModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('apilist'))
    return render(request,'change.html',{'form':form})

def apiedit(request,nid):
    """
    编辑接口
    :param request:
    :return:
    """
    obj = models.ApiManage.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = ApiModelForm(instance=obj)
        return render(request,'change.html',{'form':form})
    form = ApiModelForm(data=request.POST,instance=obj)
    if form.is_valid():
        form.save()
        return redirect(reverse('apilist'))
    return render(request,'change.html',{'form':form})

def apidel(request,nid):
    origin = reverse('apilist')
    if request.method == 'GET':
        return render(request,'delete.html',{'cancel':origin})
    models.ApiManage.objects.filter(id=nid).delete()
    return redirect(origin)

apitest/views/host_env.py
from django.shortcuts import render,redirect
from apitest import models
from apitest.form.allform import EnvModelForm
from django.urls import reverse


def envlist(request):
    env_queryset = models.RunEnv.objects.all()
    return render(request,'envlist.html',{'env_queryset':env_queryset})


def envadd(request):
    """
    添加集群环境
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = EnvModelForm()
        return render(request,'change.html',{'form':form})
    form = EnvModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('envlist'))
    return render(request,'change.html',{'form':form})


def envedit(request,nid):
    """
    编辑集群环境
    :param request:
    :return:
    """
    obj = models.RunEnv.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = EnvModelForm(instance=obj)
        return render(request,'change.html',{'form':form})
    form = EnvModelForm(data=request.POST,instance=obj)
    if form.is_valid():
        form.save()
        return redirect(reverse('envlist'))
    return render(request,'change.html',{'form':form})


def envdel(request,nid):
    origin = reverse('envlist')
    if request.method == 'GET':
        return render(request,'delete.html',{'cancel':origin})
    models.RunEnv.objects.filter(id=nid).delete()
    return redirect(origin)

apitest/views/process_request.py
import sys,time
import requests
import json



class Process_method:
    def __init__(self,host,org,app,headers):
        self.host = host
        self.org = org
        self.app = app
        self.headers = headers


    def process_get(self,url):
        try:
            allurl = "%s/%s/%s/%s" % (self.host,self.org,self.app,url)
            print('url:',allurl)
            self.r = requests.get(allurl, headers=self.headers)
            if self.r.status_code == 200:
                data = self.r.json()
                if data:
                    result = json.dumps(data, sort_keys=True, indent=2)
                    return self.r.status_code,result
                else:
                    return self.r.status_code,data
            else:
                status_code = self.r.status_code
                error_rel = json.dumps(self.r.json(), sort_keys=True, indent=2)
                return status_code,error_rel
        except (KeyError, requests.exceptions.ConnectionError) as err:
            return False,err

    def process_post(self,url,body):
        try:
            self.r = requests.post("%s/%s/%s/%s" % (self.host, self.org, self.app,url),
                                   data=json.dumps(body),
                                   headers=self.headers)
            if self.r.status_code == 200:
                data1 = self.r.json()
                if data1:
                    result = json.dumps(data1, sort_keys=True, indent=2)
                    return True,result
                else:
                    err_res = json.dumps(data1, sort_keys=True, indent=2)
                    return False,err_res
            else:
                err_res = json.dumps(self.r.json(), sort_keys=True, indent=2)
                return self.r.status_code,err_res
        except requests.exceptions.ConnectionError as err:
            return False,err

    def process_del(self,url):
        try:
            self.r = requests.delete("%s/%s/%s/%s" % (self.host, self.org, self.app, url), headers=self.headers)
            if self.r.status_code == 200:
                data1 = self.r.json()
                result = json.dumps(data1, sort_keys=True, indent=2)
                return self.r.status_code,result
            else:
                status_code = self.r.status_code
                err_res = json.dumps(self.r.json(), sort_keys=True, indent=2)
                return status_code,err_res
        except requests.exceptions.ConnectionError as err:
            return False,err


    def process_put(self,url,body):
        try:
            self.r = requests.put("%s/%s/%s/%s" % (self.host, self.org, self.app,url),
                                  data=json.dumps(body),
                                  headers=self.headers)
            if self.r.status_code == 200:
                data = self.r.json()
                result = json.dumps(data, sort_keys=True, indent=2)
                return self.r.status_code,result
            else:
                status_code = self.r.status_code
                err_res = json.dumps(self.r.json(), sort_keys=True, indent=2)
                return status_code,err_res
        except  requests.exceptions.ConnectionError as err:
            return False,err

apitest/views/start.py
from django.shortcuts import render, redirect, HttpResponse
from apitest import models
from apitest.form.allform import StartModelForm, EnvModelForm
from apitest.views.process_request import Process_method
import json
from django.urls import reverse
from django.utils import timezone


def start_test(request):
    if request.method == 'GET':
        form = StartModelForm()
        return render(request, 'start.html', {'form': form})
    env_form = StartModelForm(request.POST)

    if env_form.is_valid():
        env_nid = env_form.cleaned_data['hosts']
        api_nid = env_form.cleaned_data['api']
        print(env_nid)
        print(api_nid)
        env_queryset = models.RunEnv.objects.filter(id=env_nid).first()
        envlist = [env_queryset.host, env_queryset.token, env_queryset.appkey]
        if len(api_nid) == 1:
            api_queryset = models.ApiManage.objects.filter(id=api_nid[0]).first()
            apilist = [api_queryset.apiname, api_queryset.url, api_queryset.header, api_queryset.parmary,
                       api_queryset.body, api_queryset.methor]
            if api_queryset.parmary == None:
                apilist.remove(api_queryset.parmary)
            elif api_queryset.body == None:
                apilist.remove(api_queryset.body)
            print('env: ',envlist,apilist)
            orgname = env_queryset.appkey.split('#')[0]
            appname = env_queryset.appkey.split('#')[1]
            print('appkey:',orgname,appname)
            header = json.loads(api_queryset.header % (env_queryset.token))
            print('header:',header,type(header))
            #实例化处理请求的类
            run_test = Process_method(env_queryset.host,orgname,appname,header)
            #将参数转换成dict
            parmary = json.loads(api_queryset.parmary)

            if api_queryset.parmary != None:
                url = api_queryset.url.urlname % (parmary['url'])
                print(url)
            else:
                url = api_queryset.url
            if api_queryset.methor == 1:
                    run_test.process_post(url,api_queryset.body)
            if api_queryset.methor == 2:
                    code,result = run_test.process_get(url)
            print('result: ',code,result)
            term = models.Test_Result.objects.filter(api=api_queryset.apiname).first()
            if term:
                models.Test_Result.objects.update(api=api_queryset.apiname,
                                                status_code=code,
                                                test_content=result,
                                                test_data=timezone.now())
            else:
                models.Test_Result.objects.create(api=api_queryset.apiname,
                                                  status_code=code,
                                                  test_content=result)
            return redirect(reverse('test_result'))

    return render(request, 'start.html', {'form': env_form})


def test_result(request):
    res_queryset = models.Test_Result.objects.all()
    return render(request,'result_list.html',{'res_queryset':res_queryset})

apitest/views/url_man.py
from django.shortcuts import render,redirect
from apitest import models
from apitest.form.allform import UrlModelForm
from django.urls import reverse

def urlslist(request):
    url_queryset = models.UrlManage.objects.all()
    return render(request, 'urlslist.html', {'url_queryset':url_queryset})


def urladd(request):
    """
    增加Url
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = UrlModelForm()
        return render(request,'change.html',{'form':form})
    form = UrlModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('urllist'))
    return render(request,'change.html',{'form':form})


def urledit(request,nid):
    """
    编辑Url
    :param request:
    :return:
    """
    obj = models.UrlManage.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = UrlModelForm(instance=obj)
        return render(request,'change.html',{'form':form})
    form = UrlModelForm(data=request.POST,instance=obj)
    if form.is_valid():
        form.save()
        return redirect(reverse('urllist'))
    return render(request,'change.html',{'form':form})


def urldel(request,nid):
    origin = reverse('urllist')
    if request.method == 'GET':
        return render(request,'delete.html',{'cancel':origin})
    models.UrlManage.objects.filter(id=nid).delete()
    return redirect(origin)

apitest/views/users.py
from django.shortcuts import render,redirect
from apitest import models
from django.conf import settings
from django.urls import reverse


def login(request):
    if request.method == 'GET':
        return render(request,'login.html')
    user = request.POST.get('username')
    pwd = request.POST.get('password')
    user_obj = models.User_manage.objects.filter(username=user,password=pwd).first()
    if not user_obj:
        return render(request,'login.html',{'error':'用户名或密码错误'})

    request.session[settings.LOGIN_SUCCESS_SESSION] = 'login success'
    return redirect(reverse('start_test'))

def logout(request):
    request.session.delete()
    return redirect(reverse('login'))

apitest/templates/apilist.html
{% extends 'motherboard.html' %}

{% block content %}
    <div style="margin: 5px;">
        <a href="{% url 'apiadd' %}" class="btn btn-primary"><i class="fa fa-plus-circle" aria-hidden="true"></i>添加接口</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>接口功能</th>
            <th>Url名称</th>
            <th>请求header</th>
            <th>参数</th>
            <th>请求body</th>
            <th>请求方法</th>
            <th>操作</th>
        </tr>
        </thead>
     <tbody>
        {% for row in api_queryset %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.apiname }}</td>
                    <td>{{ row.url }}</td>
                    <td width="20%">{{ row.header }}</td>
                    <td>{{ row.parmary }}</td>
                    <td>{{ row.body }}</td>
                    <td>{{ row.get_methor_display }}</td>

                    <td>
                        <a href="{% url 'apiedit' row.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>编辑</a>
                        |
                        <a href="{% url 'apidel' row.id %}" style="color: red;"><i class="fa fa-trash-o" aria-hidden="true"></i>删除</a>
                    </td>
                </tr>
        {% endfor %}
        </tbody>
    </table>
    <div>
        <h3>参数说明：</h3>
        <p class="lead">【请求header】和【参数】要使用双引号的json串格式</p>


    </div>




{% endblock%}

apitest/templates/change.html
{% extends 'motherboard.html' %}


{% block content %}
    <form class="form-horizontal" method="post" style="width:600px; margin:0 auto; margin-top: 50px" novalidate>
        {% csrf_token %}

        {% for item in form %}
        <div class="form-group">
            <label class="col-sm-2 control-label">{{ item.label }}</label>
            <div class="col-sm-10">
                {{ item }}
                <span style="color: red;">{{ item.errors.0 }}</span>
            </div>
        </div>
        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="提 交">
            </div>
        </div>
    </form>
{% endblock %}

apitest/templates/delete.html
{% extends 'motherboard.html' %}

{% block content %}
 <div class="alert alert-danger" role="alert">
        <form method="post">
            {% csrf_token %}
            <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确定是否删除？</p>


            <div style="margin-top: 20px;">
                <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>

                <input type="submit" class="btn btn-danger btn-sm" value="确 认">
            </div>
        </form>
    </div>

{% endblock%}

apitest/templates/envlist.html
{% extends 'motherboard.html' %}

{% block content %}
    <div style="margin: 5px;">
        <a href="{% url 'envadd' %}" class="btn btn-primary"><i class="fa fa-plus-circle" aria-hidden="true"></i>添加集群环境</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>集群环境名称</th>
            <th>Token</th>
            <th>Appkey</th>
            <th>操作</th>
        </tr>
        </thead>
     <tbody>
        {% for row in env_queryset %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.host }}</td>
                    <td width="10%">{{ row.token }}</td>
                    <td>{{ row.appkey }}</td>
                    <td>
                        <a href="{% url 'envedit' row.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>编辑</a>
                        |
                        <a href="{% url 'envdel' row.id %}" style="color: red;"><i class="fa fa-trash-o" aria-hidden="true"></i>删除</a>
                    </td>
                </tr>
        {% endfor %}


        </tbody>

    </table>
{% endblock%}

apitest/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
</head>
<body>

<div style="width: 400px;margin: 0 auto;margin-top: 100px;">

    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="form-group">
            <h2 style="margin: 30px; text-align:center; color: red">请先登陆</h2>
            <label for="user" class="col-sm-3 control-label">用户名</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="user" name="username">
            </div>
        </div>
        <div class="form-group">
            <label for="pwd" class="col-sm-3 control-label">密码</label>
            <div class="col-sm-9">
                <input type="password" class="form-control" id="pwd" name="password">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-primary">提 交</button>
                <span style="color: red">{{ error }}</span>
            </div>
        </div>
    </form>
</div>
</body>
</html>

apitest/templates/motherboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试管理平台</title>
    <link rel="shortcut icon" href="{% static 'imgs/luffy-study-logo.png' %} ">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %} "/>
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/commons.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %} "/>
    <style>
        body {
            margin: 0;
        }

        .no-radius {
            border-radius: 0;
        }

        .no-margin {
            margin: 0;
        }

        .pg-body > .left-menu {
            background-color: #EAEDF1;
            position: absolute;
            left: 1px;
            top: 48px;
            bottom: 0;
            width: 220px;
            border: 1px solid #EAEDF1;
            overflow: auto;
        }

        .pg-body > .right-body {
            position: absolute;
            left: 225px;
            right: 0;
            top: 48px;
            bottom: 0;
            overflow: scroll;
            border: 1px solid #ddd;
            border-top: 0;
            font-size: 13px;
            min-width: 755px;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .luffy-container {
            padding: 15px;
        }

        .left-menu .menu-body .static-menu {

        }

        .left-menu .menu-body .static-menu .icon-wrap {
            width: 20px;
            display: inline-block;
            text-align: center;
        }

        .left-menu .menu-body .static-menu a {
            text-decoration: none;
            padding: 8px 15px;
            border-bottom: 1px solid #ccc;
            color: #333;
            display: block;
            background: #efefef;
            background: -webkit-gradient(linear, left bottom, left top, color-stop(0, #efefef), color-stop(1, #fafafa));
            background: -ms-linear-gradient(bottom, #efefef, #fafafa);
            background: -o-linear-gradient(bottom, #efefef, #fafafa);
            filter: progid:dximagetransform.microsoft.gradient(startColorStr='#e3e3e3', EndColorStr='#ffffff');
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#fafafa',EndColorStr='#efefef')";
            box-shadow: inset 0 1px 1px white;
        }

        .left-menu .menu-body .static-menu a:hover {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }

        .left-menu .menu-body .static-menu a.active {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }
    </style>
    {% block css %} {% endblock %}
</head>
<body>

<div class="pg-header">
    <div class="nav">
        <div class="logo-area left">
            <a href="#">
                <img class="logo" src="{% static 'imgs/luffy.gif' %}">
                <span style="font-size: 18px;">RestApi测试</span>
            </a>
        </div>

        <div class="left-menu left">
            <a class="menu-item">用户信息</a>
            <a class="menu-item">广告管理</a>
            <div class="menu-item">
                <span>使用说明</span>
                <i class="fa fa-caret-down" aria-hidden="true"></i>
                <div class="more-info">
                    <a href="#" class="more-item">用户操作</a>
                    <a href="#" class="more-item">操作入口</a>
                </div>
            </div>
        </div>

        <div class="right-menu right clearfix">

            <div class="user-info right">
                <a href="#" class="avatar">
                    <img class="img-circle" src="{% static 'imgs/default.png' %}">
                </a>

                <div class="more-info">
                    <a href="#" class="more-item">个人信息</a>
{#                    <a href="{% url 'logout'  %}" class="more-item">注销</a>#}
                </div>
            </div>

            <a href="{% url 'logout'  %}" class="user-menu right">注销</a>


        </div>

    </div>
</div>




<div class="pg-body">
    <div class="left-menu">
        <div class="menu-body">
            <div class="static-menu">
                <a href="{% url 'urllist' %}"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span>URL列表</a>
                <a href="{% url 'apilist' %}"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span>接口管理</a>
                <a href="{% url 'envlist' %}"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span>集群环境管理</a>
                <a href="{% url 'start_test' %}"><span class="icon-wrap"><i class="fa fa-columns" aria-hidden="true"></i></span>启动测试</a>
                <a href="{% url 'test_result' %}"><span class="icon-wrap"><i class="fa fa-columns" aria-hidden="true"></i></span>测试结果</a>
            </div>
        </div>
    </div>
    <div class="right-body">
{#        <div>#}
{#            <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">#}
{#                <li><a href="#">首页</a></li>#}
{#                <li class="active">客户管理</li>#}
{#            </ol>#}
{#        </div>#}
        {% block content %} {% endblock %}
    </div>
</div>


<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap-treeview.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap-treeview.min.js' %} "></script>
{% block js %} {% endblock %}
</body>
</html>

apitest/templates/result_list.html
{% extends 'motherboard.html' %}

{% block content %}


    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>接口功能</th>
            <th>返回状态码</th>
            <th>返回body</th>
            <th>执行日期</th>
        </tr>
        </thead>
     <tbody>
        {% for row in res_queryset %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.api }}</td>
                    <td>{{ row.status_code }}</td>
                    <td id="tree" width="30%" >{{ row.test_content }}</td>
                    <td>{{ row.test_data }}</td>

                </tr>
        {% endfor %}
        </tbody>
    </table>
    <div>


    </div>


{% endblock%}

apitest/templates/start.html
{% extends 'motherboard.html' %}

{% block content %}


{#    <table class="table table-bordered">#}
{#        <thead>#}
{#        <tr>#}
{#            <th>ID</th>#}
{#            <th>Url名称</th>#}
{#            <th>请求header</th>#}
{#            <th>Url参数</th>#}
{#            <th>请求body</th>#}
{#            <th>请求方法</th>#}
{#            <th>操作</th>#}
{#        </tr>#}
{#        </thead>#}
{#     <tbody>#}
{#        {% for row in api_queryset %}#}
{#                <tr>#}
{#                    <td>{{ row.id }}</td>#}
{#                    <td>{{ row.url }}</td>#}
{#                    <td width="20%">{{ row.header }}</td>#}
{#                    <td>{{ row.parmary }}</td>#}
{#                    <td>{{ row.body }}</td>#}
{#                    <td>{{ row.get_methor_display }}</td>#}
{##}
{#                    <td>#}
{#                        <a href="{% url 'apiedit' row.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>编辑</a>#}
{#                        |#}
{#                        <a href="{% url 'apidel' row.id %}" style="color: red;"><i class="fa fa-trash-o" aria-hidden="true"></i>删除</a>#}
{#                    </td>#}
{#                </tr>#}
{#        {% endfor %}#}
{#        </tbody>#}
{#    </table>#}


<form class="form-horizontal" method="post" style="width:600px; margin:0 auto; margin-top: 50px" novalidate>
        {% csrf_token %}

        {% for item in form %}
        <div class="form-group">
            <label class="col-sm-2 control-label">{{ item.label }}</label>
            <div class="col-sm-10">
                {{ item }}
                <span style="color: red;">{{ item.errors.0 }}</span>
            </div>
        </div>
        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="提 交">
            </div>
        </div>
    </form>




{% endblock%}

apitest/templates/urlslist.html
{% extends 'motherboard.html' %}

{% block content %}
    <div style="margin: 5px;">
        <a href="{% url 'urladd' %}" class="btn btn-primary"><i class="fa fa-plus-circle" aria-hidden="true"></i>添加URL</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>url名称</th>
            <th>功能服务</th>
            <th>操作</th>
        </tr>
        </thead>
     <tbody>
        {% for row in url_queryset %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.urlname }}</td>
                    <td>{{ row.func }}</td>

                    <td>
                        <a href="{% url 'urledit' row.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>编辑</a>
                        |
                        <a href="{% url 'urldel' row.id %}" style="color: red;"><i class="fa fa-trash-o" aria-hidden="true"></i>删除</a>
                    </td>
                </tr>
        {% endfor %}


        </tbody>

    </table>
{% endblock%}